"""Bootstraps and exposes the ChromaDB collection for the lore corpus.

Strategy: persistent on-disk Chroma at `settings.chroma_path`. On startup we
ensure the collection exists and seed any missing lore entries (idempotent —
re-running is safe and cheap).

Embeddings are generated by OpenAI with a small Chroma embedding adapter that
uses the OpenAI SDK v1+ client. If `OPENAI_API_KEY` is empty, init_chroma is a
no-op and Hermione's Notes will fail at query time with a clear error.
"""

from __future__ import annotations

import logging
from typing import Any, cast

import chromadb
from chromadb.api.types import Documents, EmbeddingFunction, Embeddings
from chromadb.config import Settings as ChromaSettings
from chromadb.telemetry.product import ProductTelemetryClient, ProductTelemetryEvent
from openai import OpenAI
from overrides import override

from app.config import settings

log = logging.getLogger(__name__)

_client = None
_collection = None


class OpenAIEmbeddingFunction(EmbeddingFunction[Documents]):
    """Chroma embedding function compatible with openai>=1.0."""

    def __init__(self, api_key: str, model_name: str) -> None:
        self._client = OpenAI(api_key=api_key).embeddings
        self._model_name = model_name

    def __call__(self, input: Documents) -> Embeddings:
        normalized_input = [text.replace("\n", " ") for text in input]
        response = self._client.create(
            input=normalized_input,
            model=self._model_name,
        )
        sorted_embeddings = sorted(response.data, key=lambda item: item.index)
        return cast(Embeddings, [item.embedding for item in sorted_embeddings])


class NoOpTelemetry(ProductTelemetryClient):
    @override
    def capture(self, event: ProductTelemetryEvent) -> None:
        return None


def init_chroma(lore_entries: list[dict[str, Any]]) -> None:
    global _client, _collection

    if not settings.openai_api_key:
        log.warning(
            "init_chroma: OPENAI_API_KEY not set — skipping Chroma bootstrap. "
            "Hermione's Notes will be unavailable until the key is provided."
        )
        return

    settings.chroma_path.mkdir(parents=True, exist_ok=True)
    _client = chromadb.PersistentClient(
        path=str(settings.chroma_path),
        settings=ChromaSettings(
            anonymized_telemetry=False,
            chroma_product_telemetry_impl=(
                "app.rag_service.knowledge_loader.NoOpTelemetry"
            ),
            chroma_telemetry_impl="app.rag_service.knowledge_loader.NoOpTelemetry",
        ),
    )

    embedding_fn = OpenAIEmbeddingFunction(
        api_key=settings.openai_api_key,
        model_name=settings.openai_embedding_model,
    )

    _collection = _client.get_or_create_collection(
        name="lore",
        embedding_function=embedding_fn,
    )

    existing_ids = set(_collection.get()["ids"])
    new_entries = [e for e in lore_entries if e["id"] not in existing_ids]
    if not new_entries:
        log.info("init_chroma: collection already has %d entries; no seeding needed.",
                 len(existing_ids))
        return

    _collection.add(
        ids=[e["id"] for e in new_entries],
        documents=[e["text"] for e in new_entries],
        metadatas=[
            {"title": e["title"], "tags": ",".join(e.get("tags", []))}
            for e in new_entries
        ],
    )
    log.info("init_chroma: seeded %d new lore entries.", len(new_entries))


def get_collection():
    if _collection is None:
        raise RuntimeError(
            "ChromaDB not initialized. Either OPENAI_API_KEY is missing, or "
            "init_chroma() was not called at startup."
        )
    return _collection
